#!/usr/local/bin/perl

use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/../../lib";

use Carp;

use CGI;
use JSON::XS;
use Data::Dumper;

use SC;
use API::Product;
use API::APIUtil;

SC->initialize;
my $default_options = API::APIUtil::config_options();

my $self = new CGI;
my $arg = ($ENV{PATH_INFO}) ? $ENV{PATH_INFO} : $ARGV[0];
my (@args) = split '/', $arg;
shift @args;
my $action = shift @args;

print "Content-Type: application/json\n\n";
if (not defined *{$action} ) {
} else {
    SC->log(0, "product: task is $action $args[0]");

	no strict 'refs';
    # perform the requested action
    #eval {
	my $json =  &{ $action }( @args );
	print JSON::XS->new->utf8->encode(API::APIUtil::stringfy($json));
    #};
}

    # Authenticated
sub from_id {
	my ($shakemap) = @_;

	my ($shakemap_id, $shakemap_version) = $shakemap =~ /(.*)-(\d+)$/;
	my $product = new API::Product->from_id($shakemap_id, $shakemap_version);

	return $product;
}

    # Authenticated
sub product_source_list {
	my ($shakemap) = @_;

	my ($shakemap_id, $shakemap_version) = $shakemap =~ /(.*)-(\d+)$/;
	my $product = new API::Product->product_source_list();

	return $product;
}

  # / (with authentication)
sub product_type {
	my ($type) = @_;

	my $product = new API::Product->product_type_list($type);

	return $product;
  };
  
sub toggle {
    # Authenticated
    my $product_id = $self->param('product_id');
    my $save_flag = $self->param('save');
    my $event;
    $event->{'result'} = new API::Product->toggle_product_display($product_id);
    $event->{'flag'} = $save_flag;
	
    return $event;
  };
  

